name: Deploy Paleo Bible to Server

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test Flask app
      run: |
        python -c "from app import app; print('✅ App imports successfully')"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to Server via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        script: |
          echo "🔄 Starting deployment..."
          
          # Navigate to project directory
          cd ~/original-bible
          
          # Pull latest changes
          echo "📥 Pulling latest changes..."
          git pull origin main
          
          # Stop current containers
          echo "🛑 Stopping containers..."
          docker-compose down
          
          # Rebuild containers with latest code
          echo "🏗️ Building containers..."
          docker-compose build --no-cache web
          
          # Start containers
          echo "🚀 Starting containers..."
          docker-compose up -d
          
          # Wait for containers to start
          sleep 10
          
          # Check status
          echo "📊 Container status:"
          docker-compose ps
          
          # Verify deployment
          echo "🔍 Verifying deployment..."
          if curl -f http://localhost >/dev/null 2>&1; then
            echo "✅ Deployment successful!"
          else
            echo "❌ Deployment may have issues - check logs"
            docker-compose logs --tail=20
          fi