name: Deploy Paleo Hebrew Bible

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask flask-cors flask-sqlalchemy flask-login werkzeug
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Test application startup
      run: |
        python -c "from app import app; print('✅ Application imports successfully')"
        
  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd ${{ secrets.PROJECT_PATH }}
          git pull origin main
          
          # Install/update dependencies
          pip install --user flask flask-cors flask-sqlalchemy flask-login werkzeug
          
          # Restart the application service
          sudo systemctl restart paleo-hebrew-bible || echo "Service restart failed - may need manual setup"
          
          # Check if application is running
          sleep 5
          curl -f http://localhost:5002/api/test || echo "⚠️ Application health check failed"
          
          echo "🚀 Deployment completed successfully!"